# Generated by Django 6.0.6 on 2026-07-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='end_by',
        ),
    ]
