# Generated by Django 6.0.6 on 2026-07-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_todolist_end_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
