# Generated by Django 6.0.6 on 2026-07-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
